In this notebook, I'm going to make all the primitive boolean functions into perceptrons. I will gve them each a 2D dataset, and have each of them learn a different primitive boolean function

In [1]:
import numpy as np

In [547]:
class arbitraryPerceptron():
    w = None    
    
    def __init__ (self):
        self.w = np.array([])
        print(self.w)
   
    def selfTrain(self, r, data, labels):
        self.w = np.random.randn(*data[0].shape)        
        weightsBeforeTraining = np.random.randn(*self.w.shape)
        
        timesTraining = 0
        
        while list(weightsBeforeTraining)!=list(self.w):
            i = 0

            timesTraining = timesTraining+1
            print("Training " + str(timesTraining) + "th time")

            weightsBeforeTraining = np.copy(self.w)

            print("Weights before training: " + str(list(weightsBeforeTraining)))
            
            for x in data:
                o = np.sign(np.dot(self.w, x))
                t = labels[i]

                if o != labels[i]:
                    for counter in range(len(self.w)):
                        self.w[counter] = self.w[counter] + r*(t-o)*x[counter]   
                i = i + 1
            
            print("Weights after training: " + str(list(self.w)))
            print("-------------")

        
        print("-------------")
        print("-------------")
        print("Weights weren't changed by training. Every datapoint in trainingset was classified correctly. Training is done")
    
    def predict(self, datapoint):
        return np.sign(np.dot(self.w,datapoint))
                



In [548]:
data = [[1, 1, 1], [1, -1, 1], [1, 1, -1], [1, -1, -1]]
data = np.array(data)

-------------------------

The first function we will learn is the AND function. As you can see, the data is binary. There are three entries into each datapoint, but the first entry is just to scale the bias. 

Each label represents what we want our algorithm to learn for its corresponding datapoint, that is, the datapoint in data that has the same index as it does. 

Since we want our perceptron to learn the AND function, (1 stands for true, -1 stands for false), only the datapoints with both coordinates as 1, should have an output of 1 (true, true -> true), while the rest should have outputs of false.

So, the label corresponding with [1, 1, 1] is 1, but with all the others (eg. [1, -1, -1]) its -1

In [549]:
andLabels = [1, -1, -1, -1]
andLabels = np.array(andLabels)

In [550]:
AND = arbitraryPerceptron()

[]


In [551]:
AND.selfTrain(.1, data, andLabels)

Training 1th time
Weights before training: [-1.3685915078328552, 2.4269348139764944, 1.491239365977455]
Weights after training: [-1.3685915078328552, 2.4269348139764944, 1.491239365977455]
-------------
-------------
-------------
Weights weren't changed by training. Every datapoint in trainingset was classified correctly. Training is done


In [552]:
AND.w

array([-1.36859151,  2.42693481,  1.49123937])

---------------

Next, we'll learn the OR function. The data will remain the same, but the labels will change. Now, binary datapoints with True, False or False, True will also be labeled as True. Only False, False will be labeled as False

In [553]:
orLabels = [1, 1, 1, -1] * 5
orLabels = np.array(orLabels)

In [554]:
OR = arbitraryPerceptron()

[]


In [555]:
OR.selfTrain(.1, data, orLabels)

Training 1th time
Weights before training: [0.8601916966810278, 0.14560216006289647, 0.6389521233845212]
Weights after training: [0.6601916966810277, 0.34560216006289646, 0.8389521233845212]
-------------
Training 2th time
Weights before training: [0.6601916966810277, 0.34560216006289646, 0.8389521233845212]
Weights after training: [0.6601916966810277, 0.34560216006289646, 0.8389521233845212]
-------------
-------------
-------------
Weights weren't changed by training. Every datapoint in trainingset was classified correctly. Training is done


In [556]:
OR.w

array([0.6601917 , 0.34560216, 0.83895212])

------------

The NAND function is just the opposite of the AND function; that is, we negate all the labels. Notive that the weights end up being the complete oppositte.

In [557]:
nandLabels = [-1, 1, 1, 1] * 5
nandLabels = np.array(nandLabels)

In [558]:
NAND = arbitraryPerceptron()

[]


In [559]:
NAND.selfTrain(.1, data, nandLabels)

Training 1th time
Weights before training: [1.376117939625867, 0.8945217177015813, 1.360713966034111]
Weights after training: [1.376117939625867, 0.4945217177015812, 0.9607139660341111]
-------------
Training 2th time
Weights before training: [1.376117939625867, 0.4945217177015812, 0.9607139660341111]
Weights after training: [1.176117939625867, 0.2945217177015812, 0.7607139660341111]
-------------
Training 3th time
Weights before training: [1.176117939625867, 0.2945217177015812, 0.7607139660341111]
Weights after training: [0.976117939625867, 0.09452171770158119, 0.5607139660341112]
-------------
Training 4th time
Weights before training: [0.976117939625867, 0.09452171770158119, 0.5607139660341112]
Weights after training: [0.7761179396258671, -0.10547828229841882, 0.36071396603411116]
-------------
Training 5th time
Weights before training: [0.7761179396258671, -0.10547828229841882, 0.36071396603411116]
Weights after training: [0.5761179396258671, -0.30547828229841884, 0.160713966034111

In [560]:
NAND.w

array([ 0.37611794, -0.50547828, -0.43928603])

-------------------

Same for NOR, the labels should be the negative of OR

In [561]:
norLabels = [-1, -1, -1, 1] * 5
norLabels = np.array(norLabels)

In [562]:
NOR = arbitraryPerceptron()

[]


In [563]:
NOR.selfTrain(.1, data, norLabels)

Training 1th time
Weights before training: [-0.025236819915359174, -0.6086053836458482, 0.34813039726040673]
Weights after training: [-0.22523681991535918, -0.40860538364584814, 0.14813039726040672]
-------------
Training 2th time
Weights before training: [-0.22523681991535918, -0.40860538364584814, 0.14813039726040672]
Weights after training: [-0.2252368199153592, -0.40860538364584814, -0.2518696027395933]
-------------
Training 3th time
Weights before training: [-0.2252368199153592, -0.40860538364584814, -0.2518696027395933]
Weights after training: [-0.2252368199153592, -0.40860538364584814, -0.2518696027395933]
-------------
-------------
-------------
Weights weren't changed by training. Every datapoint in trainingset was classified correctly. Training is done


In [564]:
NOR.w

array([-0.22523682, -0.40860538, -0.2518696 ])

--------------------------------------

Now, we will train a perceptron that returns "True" or "1" only when **at least** $m$ *of* $n$ of the features of the datapoint we feed into it are True. 

Let's make an at least 3 of 5 perceptron.

So, for example: [1, -1, -1, 1, -1, 1] would be classified as false, since there are only two features that are true, but

Think about why I have 32 different datapoints in data (clue: "different")

In [565]:
threeOfFiveData = [[1, -1, -1, -1, -1, -1], [1, -1, -1, -1, -1, 1], [1, -1, -1, -1, 1, -1],
                   [1, -1, -1, -1, 1, 1], [1, -1, -1, 1, -1, -1], [1, -1, -1, 1, -1, 1],
                   [1, -1, -1, 1, 1, -1], [1, -1, -1, 1, 1, 1], [1, -1, 1, -1, -1, -1],
                   [1, -1, 1, -1, -1, 1], [1, -1, 1, -1, 1, -1], [1, -1, 1, -1, 1, 1],
                   [1, -1, 1, 1, -1, -1], [1, -1, 1, 1, -1, 1], [1, -1, 1, 1, 1, -1],
                   [1, -1, 1, 1, 1, 1],   [1, 1, -1, -1, -1, -1], [1, 1, -1, -1, -1, 1], 
                   [1, 1, -1, -1, 1, -1],[1, 1, -1, -1, 1, 1], [1, 1, -1, 1, -1, -1], 
                   [1, 1, -1, 1, -1, 1], [1, 1, -1, 1, 1, -1], [1, 1, -1, 1, 1, 1], 
                   [1, 1, 1, -1, -1, -1], [1, 1, 1, -1, -1, 1], [1, 1, 1, -1, 1, -1], 
                   [1, 1, 1, -1, 1, 1], [1, 1, 1, 1, -1, -1], [1, 1, 1, 1, -1, 1], 
                   [1, 1, 1, 1, 1, -1], [1, 1, 1, 1, 1, 1]]


atLeastThreeOfFiveLabels = []

for d in threeOfFiveData:
    if d.count(1)>3:
        atLeastThreeOfFiveLabels.append(1)
    else:
        atLeastThreeOfFiveLabels.append(-1)
        
        
threeOfFiveData = [np.array(d) for d in threeOfFiveData]


print(len(atLeastThreeOfFiveLabels))
print(len(threeOfFiveData))



32
32


Now let's train the perceptron!!!

In [566]:
 atLeastThreeOfFivePerceptron = arbitraryPerceptron()

[]


In [567]:
atLeastThreeOfFivePerceptron.selfTrain(.1, threeOfFiveData, atLeastThreeOfFiveLabels)

Training 1th time
Weights before training: [-0.8801881935969064, 0.47952417469596315, -2.7613859112623027, -0.020922712450633704, 0.6579093632074424, 0.9432202799425864]
Weights after training: [-0.4801881935969065, 0.8795241746959632, -0.3613859112623025, 0.7790772875493663, 0.6579093632074424, 0.9432202799425864]
-------------
Training 2th time
Weights before training: [-0.4801881935969065, 0.8795241746959632, -0.3613859112623025, 0.7790772875493663, 0.6579093632074424, 0.9432202799425864]
Weights after training: [0.11981180640309352, 0.6795241746959633, 0.6386140887376975, 0.5790772875493664, 0.8579093632074424, 1.1432202799425863]
-------------
Training 3th time
Weights before training: [0.11981180640309352, 0.6795241746959633, 0.6386140887376975, 0.5790772875493664, 0.8579093632074424, 1.1432202799425863]
Weights after training: [-0.08018819359690649, 0.8795241746959632, 0.8386140887376976, 0.7790772875493663, 0.6579093632074424, 0.9432202799425864]
-------------
Training 4th time

In [568]:
atLeastThreeOfFivePerceptron.w

array([-0.08018819,  0.87952417,  0.83861409,  0.77907729,  0.65790936,
        0.94322028])

In [569]:
i = 0
correct = 0
total = 0

for datapoint in threeOfFiveData:
    if(atLeastThreeOfFivePerceptron.predict(threeOfFiveData[i]) == atLeastThreeOfFiveLabels[i]):
        correct = correct + 1
    total = total + 1
    i = i + 1

print("Our accuracy over the training set was " + str(int(correct*100/total)) + " percent, as it should be, since we trained on it!")

Our accuracy over the training set was 100 percent, as it should be, since we trained on it!


In our next program, we'll look at some function perceptrons CAN'T represent (XOR)